Switch the rs-server-staging persistance from TinyDB to PostgreSQL
RS-PYTHON/rs-helm pull request #69
Opened 2024-11-20 09:28 UTC by agrosu1978

Changes needed to persist the staging jobs from rs-server-staging in a postgresql database

2024-11-20 16:55 UTC, nleconte-csgroup requested changes

2024-11-20 16:55 UTC, nleconte-csgroup commented on charts/rs-server-staging/templates/deployment.yaml
I think you are missing a new commit from the develop about tempo.

2024-11-21 15:16 UTC, agrosu1978 commented on charts/rs-server-staging/templates/deployment.yaml
I merged with the develop branch

2024-11-27 14:18 UTC, nleconte-csgroup approved these changes
LGTM

2024-11-28 14:05 UTC, merged